spring.application.name=empleados
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/empleados
spring.datasource.username=gaspar
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql = true

# Swager ahora OpenAPI 3
# Ruta para ver el Swagger UI (Interfaz grafica)
springdoc.swagger-ui.path=/swagger-ui.html

# Ruta para el JSON de la documentacion (por si la ocupa otro equipo)
springdoc.api-docs.path=/v3/api-docs

# Paquete donde estan los Controllers
springdoc.packages-to-scan=com.gaspar.empleados.controller
